### ISSUE TITLE
Error: Class 'XoopsModules/Xbscdm/Helper' not found

### ISSUE THREAD

**Issue by ggoffy** [XoopsModulesArchive/xbs_cdm#2]
Error: Class 'XoopsModules/Xbscdm/Helper' not found in file /modules/xbs_cdm/admin/menu.php line 57

Xoops 2.5.11

**Comment by zyspec** [comment]
@ggoffy 

I assume that you're using v1.54 Beta 1 from @mambax7?

The issue is that the module directory is `xbs_cdm` and in converting the module to use namespaces `xbscdm` was used (without the underscore) to define the namespace. The module autoloader doesn't take this into account so either the namespace will need to be fixed or the directory name changed. Since the code is in 'beta' I assume @mambax7 will fix this when he gets back to working on this release.

**Comment by mambax7** [comment]
I'll take a look this weekend

**Comment by mambax7** [comment]
I couldn't replicated the issue.
But I have updated the files with some changes that I had on my PC, so maybe you can try again?

**Comment by ggoffy** [comment]
seems to work now. thank you

**Comment by mambax7** [comment]
I've discovered some other issues, so I'm working now on fixing them. Hopefully tomorrow it will be done...

**Comment by mambax7** [comment]
I think, I've fixed the issues. Please check if it works for you.
